version: '3.8'

services:
  mssql: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-${PROJECT_NAME}
    ports:
      - ${MSSQL_SERVER_PORT}:1433
    environment:
      - SA_PASSWORD=${MSSQL_PASSWORD}
      - ACCEPT_EULA=Y
      - TZ=America/Guatemala
    volumes:
      - ${MSSQL_VOLUMES}:/var/opt/mssql/data
    env_file:
      - .env
  seq:
    image: datalust/seq:latest
    container_name: seq-${PROJECT_NAME}
    environment:
      - ACCEPT_EULA=Y
      - SEQ_API_KEY=${SEQ_API_KEY}
    ports:
      - 5341:5341
      - "${SEQ_PORT}:80"
  web-api:
    container_name: web-api-${PROJECT_NAME}
    build:
      context: .
      dockerfile: GestionProductos/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - 8081:8081
      - ${WEB_API_PORT}:8080
    depends_on:
      - mssql
      - seq
    env_file:
      - .env
    
       